#!/usr/bin/env bash

#/ command: git:push: "git push script command."
#/ usage: rerun git:push [ --remote <origin>] [ --branch <>] [ --directory <>] 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: REMOTE BRANCH DIRECTORY

. "$RERUN_MODULE_DIR/lib/functions.sh" "push" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -


function pushAllBranch()
{
    remote=$1

    echo -e '\nPushing all branch.'
    res=$(git push $remote --all 2>&1 &)
    if [[ $res =~ 'Enumerating objects' || $res =~ '* [new branch]' || $res =~ 'Set trace flag' || $res =~ 'e.coding.net' ]]; then
        rerun_log info 'Push successful.'
    elif [[ $res =~ 'Everything up-to-date' ]]; then
        rerun_log warn 'Remote repository branch already latest.'
    elif [[ $res =~ "Could not read from remote repository" ]]; then
        rerun_log error "Could not read from remote repository"
        read -r -p "Press any key to retry [Y/n] " input
        case $input in
            [yY][eE][sS]|[yY])
                echo "retry..."
                pushAllBranch $remote
                ;;
        esac
    else
        res=$(cat <<- EOF
Push failed: $res
EOF
)
        rerun_log error $res
        exit
    fi
}

function pushAllTag()
{
    remote=$1

    echo -e '\nPushing all tags.'
    res=$(git push $remote --tags 2>&1 &)
    if [[ $res =~ 'Enumerating objects' || $res =~ '* [new tag]' ]]; then
        rerun_log info 'Push successful.'
    elif [[ $res =~ 'Everything up-to-date' ]]; then
        rerun_log warn 'Remote repository tags already latest. '
    elif [[ $res =~ "Could not read from remote repository" ]]; then
        rerun_log error "Could not read from remote repository"
        read -r -p "Press any key to retry [Y/n] " input
        case $input in
            [yY][eE][sS]|[yY])
                echo "retry..."
                pushAllTag $remote
                ;;
        esac
    else
        res=$(cat <<- EOF
Push failed: $res
EOF
)
        rerun_log error $res
        exit
    fi
}

gitDirectory=$(getCurrentDirPathByName "$DIRECTORY")
remote=$REMOTE
branch=$(getCurrentBranchByName "$BRANCH")

rerun_include_sh "$RERUN_MODULE_DIR/commands/push/main.sh"

# Done. Exit with last command exit status.
exit $?

